### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by awe-mt**
This resolves all the warnings/errors/deprecations from upgrading to Xcode 9.3.

The first three commits have been incorporated from `willowtreeapps/master`.

We'll need to test the graph screen to ensure that no errors have been introduced.

### CODE REVIEW

**Comment by rpranata** [comment]
@awe-mt why didnt you cherry pick?

**Comment by awe-mt** [comment]
@rpranata Did, but conflicts had to be resolved, so they end up looking like my commits.

**Comment by awe-mt** [comment]
The first 3 are cherry picked from `willowtreeapps/master`.

**Comment by awe-mt** [comment]
Tested locally - seems to be working fine.

**Comment by awe-mt** [comment]
Closing this PR because we will be working from `moneytree-patch-x.x.x` branches instead. `master` will track the `master` from upstream (`willowtreeapps/MTStackViewController/master`).

**Pull request closed without merging**
